"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import styles from "./layout.module.css";
import logo from "./images/irm1.jpeg";
import Image from "next/image";
import Link from "next/link";
import { useState } from "react";
import { FaBars } from "react-icons/fa";
const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [isActive, setIsActive] = useState(1);
  const [isSidebarOpen, setIsSidebarOpen] = useState(false);
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <div className={styles.menu_div}>
            <FaBars
              className={styles.menu}
              onClick={() => {
                setIsSidebarOpen(!isSidebarOpen);
              }}
            />
            <p className={styles.title_name}>irm</p>
          </div>
          <div className={isSidebarOpen ? styles.sidebar : styles.sidebar1}>
            {/* <Image src={logo} className={styles.logo} /> */}
            <p className={styles.name}>irm</p>
            <Link
              href="/typeB"
              onClick={() => setIsActive(0)}
              className={isActive === 0 ? styles.links_active : styles.links}
            >
              <p>reportB</p>
            </Link>
            <Link
              href="/"
              onClick={() => setIsActive(1)}
              className={isActive === 1 ? styles.links_active : styles.links}
            >
              <p>reportA</p>
            </Link>
            <Link
              href="/allReports"
              onClick={() => setIsActive(2)}
              className={isActive === 2 ? styles.links_active : styles.links}
            >
              <p>AllTypeA</p>
            </Link>
            <Link
              href="/typeBReports"
              onClick={() => setIsActive(3)}
              className={isActive === 3 ? styles.links_active : styles.links}
            >
              <p>AllTypeB</p>
            </Link>
          </div>
          <div className={styles.children}> {children}</div>
        </div>
      </body>
    </html>
  );
}
